### ISSUE TITLE
ERROR: Error during SonarScanner execution java.lang.NumberFormatException: For input string: "16-ea"

### ISSUE THREAD

**Issue by snowman2** [zaquestion/docker-sonarqube-scanner#3]
I am running into this issue with the latest push to docker hub:

https://community.sonarsource.com/t/sonarscanner-cli-java-version-check-expects-number/12075

What version was used for the last push?

**Comment by zaquestion** [comment]
Would have been the changes that came in here https://github.com/zaquestion/docker-sonarqube-scanner/pull/2/files

Let me know if I should just roll those back, or if you can put up a fix?

**Comment by snowman2** [comment]
I noticed this repo is deprecated and tried out: https://github.com/newtmitch/docker-sonar-scanner. It seems to not have the issues.

**Comment by zaquestion** [comment]
Good move 👍

**Comment by arturds** [comment]
I am running into this issue with the latest push to docker hub too, and not have older tags there

**Comment by zaquestion** [comment]
@arturds I went ahead and reverted https://github.com/zaquestion/docker-sonarqube-scanner/pull/4 -- unfortunately this build seems to have failed, and as you pointed out the older tags aren't present :( 

I'm pulling the repo now and will try to put this repo in a working state, I must say I'm shocked it's been used by so many folks (50k pulls on dockerhub) -- https://github.com/newtmitch/docker-sonar-scanner is certainly the stronger project these days.

**Comment by zaquestion** [comment]
This seems to have to do with how https://hub.docker.com/_/openjdk became the official java image, and how alpine tags are only supported for "early access" (ea) releases, so we seemingly can't produce a build that has a clean version number. Attempting to redo with `slim`

**Comment by zaquestion** [comment]
Okay, I've pushed an updated version which built successfully on docker hub and should have a clean version number. @arturds If you can let me know if this resolves your issue, I should be able to tag this version so the existing build doesn't get clobbered next time somebody wants to update it.
